version: "3.8"
services:
  dind:
    image: docker:dind
    privileged: true
    user: root
    environment: 
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
  
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    user: root
    depends_on:
      - dind
    environment:
      DOCKER_HOST: "tcp://docker:2376" 
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
      - 50000:50000
      
networks:
  jenkins:
    driver: bridge
  
volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data: